### PR TITLE
[InjectionIII.app] Bundle not found

### PR DESCRIPTION
**Pull request by MaatheusGois**
- Create alert when bundle not is found in /Applications

### CODE REVIEW

**Comment by johnno1962** [comment]
👍

**Review by krzysztofzablocki — APPROVED** [review]

**Comment by MaatheusGois** [comment]
We can set a flag #if (Simulator) to resolve this issue.

**Comment by mbger** [comment]
Yeah I was experimenting in this direction yesterday. Basically I tried to achieve the following: 

Introduce a new conditional compilation flag `DISABLE_INJECT` and modify the `#if` flags in Injection, i.e. something along those lines:

```swift
#if DEBUG && !DISABLE_INJECT
private var loadInjectionImplementation: Void = {
    guard objc_getClass("InjectionClient") == nil else { return }
#if os(macOS)
    let bundleName = "macOSInjection.bundle"
#elseif os(tvOS)
    let bundleName = "tvOSInjection.bundle"
#elseif targetEnvironment(simulator)
    let bundleName = "iOSInjection.bundle"
#elseif targetEnvironment(macCatalyst)
    let bundleName = "macOSInjection.bundle"
#else
    let bundleName = "maciOSInjection.bundle"
#endif // OS and environment conditions

    if let bundle = Bundle(path: "/Applications/InjectionIII.app/Contents/Resources/" + bundleName) {
        bundle.load()
    } else {
        assertionFailure("InjectionIII not found, verify if it's in /Applications")
    }
}()
```

Then my app target which uses `Inject` could define `DISBABLE_INJECT` whenever it's not building for the simulator and add it to `SWIFT_ACTIVE_COMPILATION_CONDITIONS`. But, alas, SwiftPM doesn't seem to support that.

**Comment by johnno1962** [comment]
Just make it a print with a ⚠️ instead of an assertionFailure. Let's keep it simple.

**Comment by mbger** [comment]
> [...] but just make it a print with a ⚠️ instead of an assertionFailure. Let's keep it simple.

For sure. I had the impression that the whole point of the PR was to crash under those circumstances. Thanks for clarifying!

**Comment by johnno1962** [comment]
Thanks for picking this up and reporting it @mbger. I guess the PR was intended to provide more feedback when the InjectionII app was not installed rather than silently failing to enable reloading. Using an `assertionFailure` however took it to the opposite extreme when you are running on a device. I think using a print statement would be a good compromise but it's your call @krzysztofzablocki.

**Pull request merged**
