### PR TITLE
Added cocoapods support

### PR DESCRIPTION
**Pull request by gcharita**
- Added podspec file (#50)
- Updated README.md

**Note:** There is already another pod registered with the name _inject_. (with lowercase '**i**') If this results to a problem, a name change in the podspec file maybe considered.

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
🙇

**Comment by lockieluke** [comment]
🙏🙏🙏

**Comment by lockieluke** [comment]
it doesn't seem to work

**Comment by lockieluke** [comment]
```ruby
  pod 'Inject', :git => 'https://github.com/krzysztofzablocki/Inject.git', :branch => 'main'
```
this works

**Comment by gcharita** [comment]
@lockieluke Yes, @krzysztofzablocki need to [submit the podspec file](https://guides.cocoapods.org/making/making-a-cocoapod.html#submitting-open-source-code) (Inject.podspec) to the cocoapods Specs Repo, in order for `pod 'Inject'` to work. That's why I am concerned about the pod's name. Sorry, I forgot to mention that before.

**Comment by krzysztofzablocki** [comment]
`pod 'InjectHotReload'`

**Pull request merged**
